#+SEQ_TODO: todo started waiting done
#+ARCHIVE: ::* archive

--------------------------------------------------------------------------------
                                 Checkers Lite
--------------------------------------------------------------------------------
                       Kingless ASCII Checkered Goodness

enough for two 82-width buffers
(set-frame-size (selected-frame) 176 76)

* Problem: Write a Checkers subset

Write a program that can play a legal game of Checkers Lite. The computer makes 
legal moves (random legal moves are acceptable for this checkers "AI").
The human player is not allowed to make illegal moves.

Checkers Lite is the same as American Checkers (also known as 
English draughts) except there is no promotion to king by moving a piece to the last 
rank (therefore stalemate is possible). Pieces move along diagonals, and jumps must 
be taken, and the board is 8 x 8. See http://en.wikipedia.org/wiki/American_checkers 
if you need a refresher on the rules.

Your program should show the game board after each move. 

If there are no legal moves, or one side is eliminated, the game is over. 

Suggested board output format as ASCII - use . for empty square, X for black, O
for white. The initial board layout might look like this 

. X . X . X . X 

X . X . X . X . 

. X . X . X . X 

. . . . . . . . 

. . . . . . . . 

O . O . O . O . 

. O . O . O . O 

O . O . O . O . 

This should take you between 1 and 4 hours to complete. Please present a working 
program along with the amount of time you spent on the program. You can do this
as a command-line program if you like (that's completely acceptable), or you can do
it as a GUI program, but a working program in 4 hours or less is your mandate.

Note: Command-line program is merely a suggestion to fit the 4 hour time
frame. If you can get more done in time, it is certainly extra credit to exceed
the minimum requirements and provide a GUI based app.

We prefer C++, but if you can do more by using a different solution (for
example, a .net or swing GUI), you can use a different language. You are also
free to use 3rd party libraries like Qt, Box2D, etc. Just make sure we can build
what you deliver. I also recommend you include a working binary in your
submission. A ready-to-build VS2010 solution is probably easiest, unless you use
Java. In that case, just provide the source and an ant build.xml or equivalent.
 
* CMDs

none yet...

* users.txt

nada

* Costs

nada

* Notes

see notebook for initial notes.

(setq c-basic-offset 3)

* TODOs

*** done Good MVC pattern for checkers?
    closed: [2012-07-13 Fri 14:24]

is MVC even the way to go?

*** done git repo for src
    closed: [2012-07-13 Fri 14:24]

  - Small proj. Just master branch? 4 hours isn't really enough to need multiple branches... probably.

  - gitignore: Makefile? Should be generated by project...

* TASKS

*** done 000: basic h/cpp template
    closed: [2012-07-10 Tue 18:34]

  - Do I have the YASnippets? I think I do
    - I do.
      - Use those, modify, copy/paste/find/replace.

*** done 001: xproj
    closed: [2012-07-10 Tue 20:09]

  - get it compiling a basic hello world main.

*** done 002: top down stubs
    closed: [2012-07-11 Wed 17:41]

  - get the basic structure in place

*** done 003: basic print out
    closed: [2012-07-11 Wed 18:15]

 - [X] board shape, info, prompt.

 - [ ] good-enough redrawing on main game loop.
   - can't use bash's clear. Gotta work on DOS prompt too.

***** ASII UI

Red (X) moved h6 to g5.

       a b c d e f g h
     +-----------------+
   8 | . X . X . X . X | 8
   7 | X . X . X . X . | 7
   6 | . X . X . X . . | 6
   5 | . . . . . . X . | 5
   4 | . . . . . . . . | 4
   3 | O . O . O . O . | 3
   2 | . O . O . O . O | 2
   1 | O . O . O . O . | 1
     +-----------------+
       a b c d e f g h

Your move: _

*** done 004: Board
    closed: [2012-07-12 Thu 00:34]

basic board functionality
 - [X] 2d array representing board
 - [X] dimensions set as public consts
 - [X] at(x,y)
 - [X] move(x,y), to(x,y)?
   - Put off til I need 'em.
 - [ ] last-move info?
   - tuple of (from, to) or how to represent bad move?
   - Put off til I need it.

_board[row][col]

Update view to use board
  - check

*** done 005: Basic Player
    closed: [2012-07-12 Thu 15:30]

Move Player.{h,cpp} to controller... they're not really models...
  - check

Make Player pure virtual class...
  - check

Make Human class
Make AiRand class
  - check

*** done 006: Human
    closed: [2012-07-12 Thu 17:34]

Get user's input in turn()
  - check

Verify
 - check

Tell board to make the move.
  - check

Prompt:
  Select piece to move (e.g. a1): _
  Move to new location (e.g. b2): _

*** done 007: board 2.0
    closed: [2012-07-12 Thu 19:58]

Now we need move() and to() and what-was-last-move.

*** done 008: more view
    closed: [2012-07-12 Thu 22:06]

Get info line working.

Consider better prompt.

*** done 009: AI
    closed: [2012-07-13 Fri 00:53]

bug in jump code...

White (O) moved from g3 to h4

      a b c d e f g h
     +-----------------+
   8 | . X . X . X . X | 8
   7 | X . . . X . X . | 7
   6 | . X . . . X . X | 6
   5 | O . X . X . . . | 5
   4 | . . . . . O . O | 4
   3 | . . O . . . . . | 3
   2 | . O . O . O . O | 2
   1 | O . O . O . O . | 1
     +-----------------+
       a b c d e f g h

jump from 3,4 to 5,6 will jump 6,7 //<- not really... no.

Black (X) jumped from e5 To g3

       a b c d e f g h
     +-----------------+
   8 | . X . X . X . X | 8
   7 | X . . . X . X . | 7
   6 | . X . . . X . X | 6
   5 | O . X . . . . . | 5
   4 | . . . . . O . O | 4
   3 | . . O . . . X . | 3
   2 | . O . O . O . . | 2
   1 | O . O . O . O . | 1
     +-----------------+
       a b c d e f g h

*** done 999: ctors
    closed: [2012-07-13 Fri 01:01]

make sure the .h file has the bad_alloc exception in there for the newing ctors

*** done 999: TODOs
    closed: [2012-07-13 Fri 16:42]

get rid of all of them

*** done 999: WINDOWS!
    closed: [2012-07-13 Fri 16:42]

  - copy to dropbox, reboot to windows.

  - install Visual Studio (2010)

  - setup VS proj.

* example

None.



# Local Variables: 
# fill-column:80
# End: 
